#!/bin/bash

sudo apt-get install -y keepass2 vim git

# Vim
#git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
#sh ~/.vim_runtime/install_awesome_vimrc.sh

# java
# read -p "Java jdk: " javaJdk
# ./scriptJava $javaJdk

# eclipse
# read -p "Eclipse C: " eclipsecFile
# read -p "Eclipse Java: " eclipseJavaFile

./scriptEclipse.sh $1 "eclipsec"
./scriptEclipse.sh $2 "eclipsejava"


